region_renames:  # может (и будет) дополняться, сюда размещаем соответствие между
                 # именем в таблице Литеха и сокращением с VGARus
  Костромская область: kost
  Ярославская область: yaro
  Хабаровский край: haba
  Калужская область: kalu
  Белгородская область: belg
  Воронежская область: voro
  Тюменская область: voro
  ЯНАО: ynen
  Челябинская область: chel
  Рязанская область: ryaz
  Амурская область: amur
  Пермский край: perm
  Тверская область: tver
  Курганская область: kurg
  Орловская область: orel
  Курская область: kurs
  Ивановская область: ivan
  Владимирская область: vlad
  Брянская область: brya
  Свердловская область: sver
  ХМАО: HMAO
appending_columns: [registry_id, depart_name, sample_number, value, status]
