paths:
  status_types: "status/get-upload-statuses"
  status_change: "status/set-upload-status"
  upload: "/api/v1/import/refilling-sample"
status:
  vga_status_types:
    'Новый': 1
    'Отправлен': 2
    'Доставлен': 3
    'Брак': 4
    'В работе': 5
    'Предварительный результат': 6
    'Секвенирован': 7
    'Готов': 8
    'Принят на секвенирование': 9
    'Брак сиквенса': 10
    'Генотипирование по ПЦР': 11
THRESHOLD: 15000
